server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  aop:
    proxy-target-class: false
  datasource:
    url: ${DATABASE_URL}/yomangjin?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    default_batch_fetch_size: 100
    open-in-view: false
#    defer-datasource-initialization: true

logging:
  level:
    '[com.example.kakao]': INFO
    '[org.hibernate.type]': TRACE

naver:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_KEY}
